---
application:
  name: "qrgen"
  project: "Test"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "qrgen"
  version: "4.4"
routers:
- name: "main-qrgen"
  routes:
  - application_name: "qrgen"
    paths:
    - "/*"
