name: Build Client

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-build]')"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install client dependencies
        working-directory: ./client
        run: npm ci
      - name: Build Vue.js App
        working-directory: ./client
        run: npm run build
