name: Client
on:
  push:
    branches-ignore:
      - master
    paths:
      - 'client/*'
  pull_request:
    branches-ignore:
      - master
    paths:
      - 'client/*'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      - name: Build Vue.js App
        working-directory: ./client
        run: npm run build
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      - name: Run eslint
        working-directory: ./client
        run: npm run lint
