name: Server

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-build]')"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Build Server
        run: npm run server:build
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-build]')"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Run tests and generate coverage report
        run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-build]')"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run server:lint